### PR TITLE
fqcn fixes, liniting fixes, wrong var fix

### PR DESCRIPTION
**Pull request by MikeCantCode**
# Overall Review of Changes

- fixed FQCNs that were named incorrectly
- fixed un-defined variable being used
- fixed lining issue with capital letters being used in a variable

## How has this been tested?

Tested against my own infrastructure.

### CODE REVIEW

**Comment by MrSteve81** [comment]
Thanks for submitting I will take a look today.

**Comment by georgenalen** [comment]
@MikeCantCode, the changes look good. The one thing that needs to be updated is the signed-off-by on the commit is missing. That is an additional DCO piece that we check for on top of the GPG signature, basically we require both. Let us know if you need some help getting the signed-off-by in the commit. 

-George

**Comment by MikeCantCode** [comment]
@georgenalen I think that it should be all set now. Thanks!

**Comment by georgenalen** [comment]
> @georgenalen I think that it should be all set now. Thanks!

Hmm it looks like DCO I still failing. If you click on the details for DCO you can see the hash and the reason for the failure. 

-George

**Comment by mfann-or** [comment]
Ahhh I see. Thanks for bearing with me. The DCO check is passing now.

**Comment by MikeCantCode** [comment]
Ahhh I see. Thanks for bearing with me. The DCO check is passing now.

**Comment by MikeCantCode** [comment]
@georgenalen Can you take another look when you have a chance? Thanks!

**Review by uk-bolly — APPROVED** [review]
Great PR and feedback

**Pull request merged**
