### PR TITLE
Fixes #23, fixes other bad var and conditional

### LINKED ISSUE #23: Bad conditionals make Backup Domain Controllers evaluate Member Server rules rather than Domain Controller rules
[Here](https://github.com/ansible-lockdown/Windows-2019-STIG/blob/7428e8d5eff0a4151dc93ad3925d12d2e8c195d1/tasks/cat1.yml#L38) is one example of many where the role needs to update this conditional to account for Backup Domain Controllers.

Issue:

Bad conditionals make Backup Domain Controllers evaluate Member Server rules rather than Domain Controller rules

Possible Solutions:

1. The conditional could use the same Ansible fact, but change the logic.
``` yaml
when:
  - "'domain controller' in ansible_windows_domain_role"
```

2. The conditional could use a different Ansible fact that is the same across Domain Controller types.
```yaml
when:
  - ansible_os_product_type == "domain_controller"
```

### PR DESCRIPTION
**Pull request by MikeCantCode**
# Overall Review of Changes

Fixes #23, fixes other bad var and conditional

## Issue Fixes

Fixes #23 

## Enhancements

N/A

## How has this been tested?

N/A

### CODE REVIEW

**Comment by georgenalen** [comment]
@MikeCantCode, 
 Thanks for the PR and I have a question about the changes. I'm wondering the reason for the bad var and conditional flag for the ansible_windows_domain_role var? Looking at ansible_facts that is a variable that is there but is more detailed in noting primary vs secondary domain controller which allows for more control on tasks that can only be used on a primary or secondary domain controller. 

-George

**Comment by mfann-or** [comment]
Replying here along with Discord.

Nope, I don't have a bigger reason for selecting the `ansible_os_product_type` over `ansible_windows_domain_role`. I identified 2 different ways in issue #23 and just committed to one of them for the PR. We could go with something like `"'domain controller' in ansible_windows_domain_role"` instead -- no issues here on my side.

Now with that being said, I didn't do an exhaustive look at every rule I updated to ensure that they should apply to all DCs -- and not just Primary DCs. There could very well be some rules that should only be applied to Primary DCs. None of the ones I looked at appeared to be that way to me -- but I may have missed something.

**Comment by MikeCantCode** [comment]
Replying here along with Discord.

Nope, I don't have a bigger reason for selecting the `ansible_os_product_type` over `ansible_windows_domain_role`. I identified 2 different ways in issue #23 and just committed to one of them for the PR. We could go with something like `"'domain controller' in ansible_windows_domain_role"` instead -- no issues here on my side.

Now with that being said, I didn't do an exhaustive look at every rule I updated to ensure that they should apply to all DCs -- and not just Primary DCs. There could very well be some rules that should only be applied to Primary DCs. None of the ones I looked at appeared to be that way to me -- but I may have missed something.

**Comment by georgenalen** [comment]
the windows domain role I think uses the text Primary domain controller and Secondary domain controller (also Member server and Stand-alone server). Maybe we do "'Primary domain controller' in ansible_windows_domain_role"? Does that make sense? 

-George

**Comment by MikeCantCode** [comment]
Correct -- that's how Ansible sets those facts. But the role already has the logic you recommend with the conditional `ansible_windows_domain_role == "Primary domain controller"`.

It doesn't resolve the issue where secondary DCs (`ansible_windows_domain_role == "Secondary domain controller"`) are not evaluating the DC rules. I'm pretty sure secondary DCs should have STIG rules applied the same as Primary DCs. STIG doesn't make a discrepancy there.

So in order to make sure both DC types are evaluated, we need that conditional updated. This PR used a different fact that is consistent across both DC types -- but we could also use `"'domain controller' in ansible_windows_domain_role"` for example.

**Comment by georgenalen** [comment]
Oh duh, I'm dumb. Yeah domain controller is in string and it still works. Sorry it just clicked, for some reason I was in the mindset of matching text exactly in there for some reason. Yeah I like the "'domain controller' in ansible_windows_domain_role" option. 

-George

**Comment by frederickw082922** [comment]
Thank you @MikeCantCode appreciate you taking the time to submit your PR. Unfortunately, we closed your PR due to keeping PDC vs Member Server vs Standonle due to the testing pipeline baseline for clients. We have noted the secondary domain controller behavior in our backlog. When the secondary controller baseline gets addressed, we will make the change to all of DC controls. Thank you for your patience and understanding.

**Pull request closed without merging**
